config/routes.rb
Rails.application.routes.draw do

  get 'screens/home'
  root 'screens#home'

get 'new' => 'screens#new'

  post 'new' => 'screens#upload'

  get 'screens/show' => 'screens#show'
  get 'contact' => 'screens#contact' , as: :contact

  get 'help' => 'screens#help' , as: :help

  get 'about' => 'screens#about' , as: :about

end

app/models/user.rb
class User < ActiveRecord::Base

  validates_presence_of :first_name, :message => "Please enter your first name"
  validates_presence_of :last_name, :message => "Please enter your last name"
  validates_presence_of :email, :message => "Please enter your email"
  validates_presence_of :mailing_address, :message => "Please enter your mailing address"
  validates_presence_of :phone_number, :message => "Please enter your phone number"
  validates_presence_of :zip_code, :message => "Please enter your zip code"

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/screens_controller.rb
class ScreensController < ApplicationController
  def home
  end
def new
  @user= User.new
end
  def upload


    @user = User.new(user_params)
    if @user.save

      redirect_to '/screens/show'
    else
      render '/screens/new'
    end
    end

  def contact
  end

  def help
  end

  def about
  end

  def show
    @user = User.all

  end
  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :mailing_address, :phone_number, :zip_code, :photo)

  end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/screens_helper.rb
module ScreensHelper
end

app/views/layout_styles/_layoutbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><b>Owens Corning Favorite Pink Panther</b></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", root_path %></li>
       <li><%= link_to "Upload Image", new_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "About", about_path %></li>

      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OwensCorning</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layout_styles/layoutbar'%>
<%= yield %>

</body>
</html>

app/views/screens/about.html.erb
<div class="jumbotron">
  <div class="container">


    <h2>Owens Corning</h2>


    <p>

      Owens Corning is a global company that develops and produces insulation, roofing, and fiberglass composites.
      It was formed in 1935 as a partnership between two major American glassworks, Corning Glass Works and Owens-Illinois.
      The company employs approximately 15,000 people around the world.
      Owens Corning has been a Fortune 500 company every year since the list was created in 1955.
    </p>
  </div>
</div>



<hr>

<br>
<br>
<br>
<br>
<br>
<footer>
  <p>&copy;1996-2015 Owens Corning</p>
</footer>
</div> <!-- /container -->

app/views/screens/contact.html.erb
<br>
<br>


<div class="jumbotron">
  <div class="container">


    <h2>Contact Information</h2>



<br>
     <h4> 1 Owens Corning Pkwy · (419) 248-8000</h4>
      <br>
      <h4>Toledo OH 43659</h4>
    <br>

      <h4>www.owenscorning.com</h4>
<br>
    </p>
  </div>
</div>

<br>
<br>
<br>
<br>
<br>
<footer>
  <p>&copy;1996-2015 Owens Corning</p>
</footer>

app/views/screens/help.html.erb
<br>
<br>
<div class="jumbotron">
  <div class="container">


    <h2>Help</h2>


    <p>

      <h4>Please upload pink panther images contact (419) 248-8000 for any help</h4>

    </p>
  </div>
</div>

<br>
<br>
<br>
<br>
<br>
<footer>
  <p>&copy;1996-2015 Owens Corning</p>
</footer>

app/views/screens/home.html.erb
<div class="jumbotron">
  <div class="container">


   <b><h3>Welcome to Owens Corning Favourite Pink Panther Page. Please upload your favourite pink panther image by clicking --->"Upload Image" Tab</h3></b>

   </p>
  </div>
</div>



  <hr>
<br>
<br>



<br>
<br>
<br>
<br>
<br>
  <footer>
    <p>&copy;1996-2015 Owens Corning</p>
  </footer>
</div> <!-- /container -->

app/views/screens/new.html.erb
<h3>Please Upload Image Here</h3>
<% @user.errors.messages.each do |msg| %>
    <li><%= msg[0]%>----<%= msg[1][0]%></li>

<% end %>
<br>
<br>

<div class="jumbotron">
  <div class="container">



<%= form_for :user do |u| %>
    <div>
      First Name:  <%= u.text_field :first_name %><br><br>
      Last Name: <%= u.text_field :last_name %><br><br>

      Email:  <%= u.text_field :email %><br><br>
      Mailing Address: <%= u.text_field :mailing_address %><br><br>
      Phone Number: <%= u.text_field :phone_number %><br><br>
      Zip Code: <%= u.text_field :zip_code %><br><br>
      Image Upload: <%= u.file_field :photo %><br><br>


    </div>



      <div>
      <%= u.submit "Sign Up" %>
      </div>
      <% end %>

</div>
  </div>
<br>
<br>
<br>
<br>
<br>
<footer>
  <p>&copy;1996-2015 Owens Corning</p>
</footer>

app/views/screens/show.html.erb
<div class="jumbotron">
  <div class="container">

    <div>
      <p>Thank you for uploading your favourite Pink Panther Image</p>

<br>
      <br>

      <p>Here are the Uploaded Images</p>

      <% @user.each do |u| %>


          <div>
           <h3>First Name :</h3> <h3><%= u.first_name %></h3>
            <td><%= image_tag u.photo.url(:medium) %></td>



            <hr>

          </div>
      <% end %>
      <hr>

    </div>
</div>
  </div>


    <br>
    <br>
    <br>
    <br>
    <br>
    <footer>
      <p>&copy;1996-2015 Owens Corning</p>
    </footer>